name: push_ci
run-name: Push CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  macos:
    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false
    runs-on: macos-latest
    env: 
      BUILD_REASON: "PullRequest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run macOS Build Script
        run: ./ci/azure/macos_script

      - run: |
          zig version
