name: push_ci
run-name: Push CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  linux:
    runs-on: [self-hosted, Linux, x64]
    env: 
      ARCH: "x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run Build Script
        run: ./ci/linux/build.sh
  macos:
    runs-on: [self-hosted, macOS, ARM64]
    env: 
      ARCH: "aarch64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # - name: Run Build Script
      #   run: ./ci/macos/build.sh
  windows:
    runs-on: [self-hosted, Windows, x64]
    env: 
      ARCH: "x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # - name: Run Build Script
      #   run: ./ci/windows/build.ps1
